---
version: "3.3"
services:
  rest-to-tts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-to-tts
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    image: "blastbeng/discord-voicebot-api:1.0.0"
    restart: "no"
    volumes:
      - ".env:/app/.env"
      - "./config:/app/config"
      - "/tmp/rest-to-tts:/tmp/rest-to-tts"
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    entrypoint: ./entrypoint.sh
    ports:
      - "5101:5101"
    networks:
      - caching
  redis:
    image: redis
    container_name: rest-to-tts-redis
    networks:
      - caching
    restart: "no"
networks:
  caching:
    driver: bridge


